configuration: Release

init:
  - cmd: set
  
install:
  - cmd: appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - cmd: nuget install GitVersion.CommandLine -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre  
  - cmd: nuget install gitlink -SolutionDir %APPVEYOR_BUILD_FOLDER% -Verbosity quiet -ExcludeVersion -pre
     
before_build:
  - cmd: nuget restore src\Humanizer.sln
  - cmd: '.\packages\GitVersion.CommandLine\tools\GitVersion.exe /l console /output buildserver /updateAssemblyInfo'
  
build:
  verbosity: normal
  parallel: true
  project: src\Humanizer.sln
  
after_build:
  - cmd: '.\packages\gitlink\lib\net45\GitLink.exe . -f src\Humanizer.sln -u https://github.com/MehdiK/Humanizer -s %APPVEYOR_REPO_COMMIT% -errorsaswarnings'
  - cmd: nuget pack src\Humanizer.nuspec -version "%GitVersion_NuGetVersion%" -prop "target=%CONFIGURATION%" -NoPackageAnalysis
  - cmd: appveyor PushArtifact "Humanizer.%GitVersion_NuGetVersion%.nupkg"  
  
test:
  assemblies:
    - '**\*.Tests.dll'
  
deploy:
  provider: NuGet
  server: https://www.myget.org/F/humanizer/api/v2/package
  api_key:
    secure: bmqlJK8a5HYiUXOT99HXT1j7JiM5+fpR4kHhxIC30oaaEXbv94f0fKdiKlU1QC/l
  artifact: /.*\.nupkg/